apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: docker-app
          image: samplecamper/study-project
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
spec:
  selector:
    app: docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
